projectpartnerproject/projectpartnerapp/urls.py
from django.conf.urls import url, include
from django.urls import path
# from rest_framework import routers
# from rest_framework.authtoken.views import obtain_auth_token
from .views import *
from .views import register_user
from .views import register_form

app_name = "projectpartnerapp"

urlpatterns = [
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^register$', register_user, name='register'),
    url(r'^register/form$', register_form, name='registerform'),


    url(r'^$', home, name='home'),
    url(r'^projects$', project_list, name='projects'),
    url(r'^project/form$', project_form, name='project_form'),
    path('projects/<int:project_id>/', project_details, name='project'),
    url(r'^projects/(?P<project_id>[0-9]+)/form$', project_edit_form, name='project_edit_form'),



    url(r'^owners$', owner_list, name='owners'),

    url(r'^materials$', material_list, name='materials'),
    url(r'^material/form$', material_form, name='material_form'),
    path('materials/<int:material_id>/', material_details, name='material'),
    url(r'^materials/(?P<material_id>[0-9]+)/form$', material_edit_form, name='material_edit_form'),


    url(r'^tools$', tool_list, name='tools'),
    url(r'^new-tool/form$', new_tool_form, name='new_tool_form'),
    path('tools/<int:tool_id>/', tool_details, name='tool'),
    url(r'^tools/(?P<tool_id>[0-9]+)/form$', tool_edit_form, name='tool_edit_form'),


    url(r'^project-tools$', project_tool_list, name='project_tools'),
    url(r'^project-tool/form$', project_tool_form, name='project_tool_form'),
    path('project-tools/<int:projecttool_id>/', project_tool_details, name='project_tool'),




]

projectpartnerproject/projectpartnerproject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from projectpartnerapp.models import *



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('projectpartnerapp.urls')),



]

projectpartnerproject/projectpartnerapi/models.py
from django.db import models

# Create your models here.

projectpartnerproject/projectpartnerapp/models/material.py
from django.db import models
from .project import Project
from .project import Owner

class Material(models.Model):
# Create a model for a project material. Set blank=True and null=True so some properties can be initially set as NULL for future editing
# and the form fields can be left blank
# Set an owner Foreign Key property so you can filter data to be displayed by the user logged in
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=50, null=True, blank=True)
    cost = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING, related_name='materials')
    image = models.ImageField(upload_to='images/', null=True, blank=True, height_field='url_height', width_field='url_width')
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

projectpartnerproject/projectpartnerapp/models/owner.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Owner(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', null=True, blank=True, max_length=300, height_field='url_height', width_field='url_width')

# Auto create an instance of an owner when a new user registers
@receiver(post_save, sender=User)
def create_owner(sender, instance, created, **kwargs):
    if created:
        Owner.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_owner(sender, instance, **kwargs):
    instance.owner.save()

projectpartnerproject/projectpartnerapp/models/project.py
from django.db import models
from django.db.models import F
from .owner import Owner

class Project(models.Model):
    # Set an owner Foreign Key property so you can filter data to be displayed by the user logged in

    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    width = models.IntegerField(default=0)
    length = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @property
    def location_sq_footage(self):
        return self.width * self.length

projectpartnerproject/projectpartnerapp/models/projecttool.py
from django.db import models
from .project import Project
from .tool import Tool

class ProjectTool(models.Model):

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tool_list')
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE)

projectpartnerproject/projectpartnerapp/models/tool.py
from django.db import models
from .project import Owner

class Tool(models.Model):
# Set an owner Foreign Key property so you can filter data to be displayed by the user logged in


    name = models.CharField(max_length=50)
    manufacturer = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    cost = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, default=0.00)
    own = models.BooleanField()
    image = models.ImageField(upload_to='images/', null=True, blank=True, max_length=300, height_field='url_height', width_field='url_width')
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

projectpartnerproject/projectpartnerapi/views.py
from django.shortcuts import render

# Create your views here.

projectpartnerproject/projectpartnerapp/views/connection.py
class Connection:
    db_path = "/Users/jeffh/workspace/capstone/backend/project-partner/projectpartnerproject/db.sqlite3"

projectpartnerproject/projectpartnerapp/views/home.py
import sqlite3
from django.shortcuts import render
from projectpartnerapp.models import Project
from .connection import Connection


def home(request):
    if request.method == 'GET':
        with sqlite3.connect(Connection.db_path) as conn:
            conn.row_factory = sqlite3.Row
            db_cursor = conn.cursor()

            db_cursor.execute("""
            select
                p.id,
                p.owner_id,
                p.name,
                p.description,
                p.location,
                p.length,
                p.width,
                p.completed
            from projectpartnerapp_project p
            """)

            all_projects = []
            dataset = db_cursor.fetchall()

            for row in dataset:
                project = Project()
                project.id = row['id']
                project.name = row['name']
                project.description = row['description']
                project.location = row['location']
                project.width = row['width']
                project.length = row['length']
                project.owner_id = row['owner_id']
                project.completed = row['completed']

                all_projects.append(project)

        template = 'home.html'
        context = {
            'all_projects': all_projects
        }

        return render(request, template, context)

projectpartnerproject/projectpartnerapp/templates/home.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% bootstrap_messages %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% bootstrap_css %}
    <title>Project Partner</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/projects.css' %}" />
    {% endblock %}
  </head>
  <body>
    {% block content %}
{% comment %} The homepage only displays the users Open projects and they can start a new project {% endcomment %}
    {% if request.user.is_authenticated %}
    <div class="header">
      <h2>Welcome, {{ user.first_name }}. Here are your open projects.</h2>

    <button class="btn btn-secondary"><a class="text-decoration:none" href="{% url 'projectpartnerapp:project_form' %}">Create New Project</a></button>
    <button class="btn btn-secondary"><a class="text-decoration:none" href="{% url 'projectpartnerapp:project_tool_form' %}">Add Project Tools</a></button>
    <button class="btn btn-secondary"><a class="text-decoration:none" href="{% url 'projectpartnerapp:material_form' %}">Add Project Materials</a></button>
  </div>
    <ul class="projects" style="list-style-type:none">
    {% for project in all_projects %}
      {% if project.owner_id == user.id%}
          {% if project.completed == 0 %}
          <div class="project">
           <li class="project__title"> <strong>Project Name:</strong> {{ project.name }}</li>
            <li class="project__description"><strong>Description:</strong> {{project.description}}</li>
            <li class="project__description"><strong>Location:</strong> {{project.location}}</li>
            <li class="project__description"><strong>Width:</strong> {{project.width}} ft.</li>
            <li class="project__description"><strong>Length:</strong> {{project.length}} ft.</li>
            <li class="project__description"><strong>Square Footage:</strong> {{project.location_sq_footage}} ft.</li>
            {% if project.completed == 0 %}
            <li class="project__description"><strong>Project Completed:</strong> No</li>
            {% elif project.completed == 1 %}
            <li class="project__description"><strong>Project Completed:</strong> Yes</li>
            {% endif %}
            <button class="btn btn-secondary"> <a href="{% url 'projectpartnerapp:project' project.id %}">Details </a></button>

          {% endif %}
          <br></br>
          </div>
      {% endif %}


    {% endfor %}
    </ul>
      {% else %}
          <h2>Welcome! Please Login or Register.</h2>
    {% endif %}
    {% endblock %}

    {% bootstrap_javascript jquery='full' %}
  </body>
</html>

projectpartnerproject/projectpartnerapp/templates/materials/detail.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Project Partner</title>
  </head>
  <body>
    {% block content %}
{% comment %} Individual display of a single material for the user logged in {% endcomment %}
    <h1>Materials in Inventory</h1>

    <ul style="list-style-type:none">
    {% for material in all_materials %}

            <li>Material Name: {{ material.name }}</li>
            <li>Description: {{material.description}}</li>
            <li>Cost: {{material.cost}}</li>
            <li>Quantity: {{material.quantity}}</li>
            <li>Project: {{material.project_id}}</li>
            <br></br>
    {% endfor %}
{% comment %} Allows user to delete or edit the selected material {% endcomment %}
    </ul>
    <form action="{% url 'projectpartnerapp:material' material.material_id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete Material</button>
    </form>

    <form action="{% url 'projectpartnerapp:material_edit_form' material.material_id %}" method="GET">
            {% csrf_token %}
            <button>Edit Material</button>
    </form>



    {% endblock %}

  </body>
</html>

projectpartnerproject/projectpartnerapp/templates/materials/list.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Project Partner Materials</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/projects.css' %}" />
    {% endblock %}
  </head>
  <body>
    {% block content %}
    <div class="header">
    <h1>{{ user.first_name }}'s Materials</h1>
    </div>
    <ul class="projects" style="list-style-type:none">
    {% for material in all_materials %}
          <div class="resource">
            <li><strong>Material Name:</strong> {{ material.name }}</li>
            <li><strong>Description:</strong> {{material.description}}</li>
            <li><strong>Cost:</strong> {{material.cost}}</li>
            <li><strong>Quantity:</strong> {{material.quantity}}</li>
            <li><strong>Project:</strong> {{material.project.name}}</li>
            <form action="{% url 'projectpartnerapp:material_edit_form' material.id %}" method="GET">
                <input type="hidden" name="next" value="{{ request.path }}">

                <button>Edit Material Details</button>
            </form>
            <form action="{% url 'projectpartnerapp:material' material.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="actual_method" value="DELETE">
                <button>Delete Material</button>
            </form>
          </div>
    {% endfor %}
    </ul>

    {% endblock %}
  </body>
</html>

projectpartnerproject/projectpartnerapp/templates/owners/list.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Project Partner Owners</title>
  </head>
  <body>
    {% block content %}

    <h1>Owners</h1>

    <ol>
    {% for owner in all_owners %}
        <li>{{ owner.first_name }} {{ owner.last_name }}</li>
    {% endfor %}
    </ol>
    {% endblock %}
  </body>
</html>

projectpartnerproject/projectpartnerapp/templates/project_tools/tool_select_form.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="{% static 'styles/multiselect.css' %}" rel="stylesheet" type="text/css">
    <title>Project Tools</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/projects.css' %}" />
    {% endblock %}
  </head>
  <body>
    {% block content %}
{% comment %} Step 2 in the new project creation process allows the user to select multiple tools that are in their
tool inventory from a multiselect dropdown {% endcomment %}

  <div class="projects">
    <div class="project">
    <h1>Step 2: Add Tools</h1>
    <form action="{% url 'projectpartnerapp:project_tools' %}" method="post">
      {% csrf_token %}
      <fieldset class="project__title">
          <label for="project">Add to Project: </label>
          <select id="project" type="text" name="project_id">
                {% for project in all_projects %}
                    <option value="{{ project.id }}">{{ project.name }}</option>
                {% endfor %}
          </select>
      </fieldset>

      <h3 class="project__title">Select Multiple Tools</h3>
{% comment %} The multiselect dropdown with checkboxes to allow user to check multiple tools to add to their project {% endcomment %}
      <fieldset class="project__description">
          <select id="tool_id" name="multicheckbox[]" multiple="multiple" class="4colactive">
          {% for tool in all_tools %}
                    <ul class= "list-unstyled">
                    <option value="{{ tool.id }}">{{ tool.name }}</option>
                    </ul>
                {% endfor %}
          </select>
      </fieldset>
      <input class="btn btn-secondary btn-lg" type="submit" value="Final Step" />
    </form>
{% comment %} If the tool they want to add is not in their inventory they can add a new tool to inventory {% endcomment %}
      <h3>Don't have the tool in your inventory?</h3>
      {% comment %} <input type="hidden" name="next" value="/project-tool/form"> {% endcomment %}
      <button class="btn btn-secondary"> <a href="{% url 'projectpartnerapp:new_tool_form' %}">Add New Tool </a></button>
    </div>
    </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="{% static 'scripts/multiselect.js' %}"></script>
  <script>
  $('select[multiple]').multiselect({
      columns: 2,
      placeholder: 'Select options'
  });
  </script>

  {% endblock %}

  </body>
</html>

projectpartnerproject/projectpartnerapp/templates/projects/list.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <title>Project Partner</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/projects.css' %}" />
    {% endblock %}
  </head>
  <body>
    {% block content %}
{% comment %} This will list all the users project Open and Closed for reference {% endcomment %}
    <div class="header">
    <h2 class="project__title">All {{ user.first_name }}'s Projects</h2>
    <button class="btn btn-secondary"><a style="text-decoration:none;" href="{% url 'projectpartnerapp:project_form' %}">Create New Project</a></button>
    <button class="btn btn-secondary"><a class="text-decoration:none" href="{% url 'projectpartnerapp:project_tool_form' %}">Add Project Tools</a></button>
    <button class="btn btn-secondary"><a class="text-decoration:none" href="{% url 'projectpartnerapp:material_form' %}">Add Project Materials</a></button>
    </div>
    <ul class="projects" style="list-style-type:none">
    {% for project in all_projects %}
      {% if project.owner_id == user.id%}
        <div class="project">
           <li class="project__title"><strong> Project Name:</strong> {{ project.name }}</li>
            <li class="project__description"><strong>Description:</strong> {{project.description}}</li>
            <li class="project__description"><strong>Location:</strong> {{project.location}}</li>
            <li class="project__description"><strong>Width:</strong> {{project.width}} ft.</li>
            <li class="project__description"><strong>Length:</strong> {{project.length}} ft.</li>
            <li class="project__description"><strong>Square Footage:</strong> {{project.location_sq_footage}} ft.</li>
            {% if project.completed == 0 %}
            <li class="project__description"><strong>Project Completed:</strong> No</li>
            {% elif project.completed == 1 %}
            <li class="project__description"><strong>Project Completed:</strong> Yes</li>
            {% endif %}
            <button class="btn btn-secondary"> <a href="{% url 'projectpartnerapp:project' project.id %}">Details </a></button>
        </div>

      {% endif %}


    {% endfor %}
    </ul>
    {% endblock %}
  </body>
</html>

projectpartnerproject/projectpartnerapp/templates/projects/project_edit_form.html
{% extends 'shared/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/projects.css' %}" />
    {% endblock %}
    <link href="{% static 'styles/multiselect.css' %}" rel="stylesheet" type="text/css">
    <title>Project Partner</title>
  </head>
  <body>
    {% block content %}
    {% comment %} This builds a project edit form using three database tables for projects, tools, and materials and
    allows the user to edit each section. Project details and tools can be updated together. Materials can be edited individually {% endcomment %}
  <div class="projects">
    <div class="edit">
        <h1 class="project__title"><strong>Edit Project</strong></h1>

        <form action="{% url 'projectpartnerapp:project' project.id %}" method="post">

          {% csrf_token %}
          <input type="hidden" name="project_id" value="{{project.id}}">
          <fieldset class="project__description">
              <label for="name">Project Name: </label>
              <input id="name" type="text" name="name" placeholder="Name Your Project" value="{{ project.name}}">
          </fieldset>
          <fieldset class="project__description">
              <label for="description">Description: </label>
              <input style=" height: 100px; width:200px; "id="description" type="text" name="description" placeholder="Described Project" value="{{ project.description }}">
          </fieldset>
          <fieldset class="project__description">
              <label for="location">Location: </label>
              <input id="location" type="text" name="location" placeholder="Area of Home" value="{{ project.location }}">
          </fieldset>
          <fieldset class="project__description">
              <label for="width">Width: </label>
              <input id="width" type="text" name="width" placeholder="Ex. 14" value="{{ project.width }}">
              <label for="width">feet</label>
          </fieldset>
          <fieldset class="project__description">
              <label for="length">Length: </label>
              <input id="length" type="text" name="length" placeholder="Ex. 14" value="{{ project.length }}">
              <label for="width">feet</label>
          </fieldset>
          <fieldset >
              <p class="project_description"><strong>Mark Project Complete</strong></p>
              <label for="completed"> Yes: </label>
              <input id="completed" type="checkbox" name="completed" value=1>
              <label for="completed"> No: </label>
              <input id="completed" type="checkbox" name="completed" value=0>
          </fieldset>

{% comment %} This is the same multiselect dropdown to add more tools to a project {% endcomment %}
            <fieldset class="project__title" style="list-style-type: none;">
                <label for="tool_id"><strong>Add Tools To Project:</strong> </label>
                <select style="list-style-type: none;" id="tool_id" name="multicheckbox[]" multiple="multiple" class="4colactive removeBullet">
                {% for tool in all_tools %}
                          <option style="list-style-type:none" value="{{ tool.id }}">{{ tool.name }}</option>
                      {% endfor %}
                </select>
            </fieldset>
          <input type="hidden" name="actual_method" value="PUT">
          <input type="submit" value="Update" />
        </form>
        <br></br>
  {% comment %} This displays the initial tools that were added to the project. They can be deleted if necessary {% endcomment %}
        <h3 class="project__title"><strong>Current Project Tools</strong></h3>
            <ul style="list-style-type:none">
                    {% for project_tool in project.tool_list.all %}
                        <li id="{{project_tool.tool.id}}" name="{{project_tool.tool.id}}"> {{project_tool.tool.name}}</li>
                        <form action="{% url 'projectpartnerapp:project' project.id %}" method="POST">
                        <input type="hidden" id="tool_id" name="tool_id" value={{project_tool.tool.id}}>
                        {% csrf_token %}
                        <input type="hidden" name="actual_method" value="DELETE">
                        <button>Delete</button>
                        </form>
                    {% endfor %}
            </ul>
            <br></br>
        <h3 class="project__title"><strong>Your Project Materials</strong></h3>
{% comment %} Edit, Delete an initial material or add a new material {% endcomment %}
              {% for material in project.materials.all %}

                <li class="project_description">Material Name: {{ material.name }}</li>
                <li class="project_description">Description: {{material.description}}</li>
                <li class="project_description">Cost: {{material.cost}}</li>
                <li class="project_description">Quantity: {{material.quantity}}</li>
                <form action="{% url 'projectpartnerapp:material_edit_form' material.id %}" method="GET">
                {% csrf_token %}
                <input type="hidden" name="next" value="/projects">
                <button>Edit Material Details</button>
                </form>
                <form action="{% url 'projectpartnerapp:material' material.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="actual_method" value="DELETE">
                <button>Delete Material</button>
                </form>
              {% endfor %}
                <h3 class="project__title"><strong>Need to Add Materials?</strong></h3>
                <button><a href="{% url 'projectpartnerapp:material_form' %}">Add New Material</a></button>
      </div>
    </div>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="{% static 'scripts/multiselect.js' %}"></script>
    <script>
    $('select[multiple]').multiselect({
        columns: 2,
        placeholder: 'Select options'
    });
    </script>
  {% endblock %}
  </body>
</html>

projectpartnerproject/projectpartnerapp/templates/shared/base.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Project Partner</title>
    <link href="https://fonts.googleapis.com/css?family=Chilanka|Dekko|Kavivanar|Walter+Turncoat&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />
    {% block css %}
    {% endblock %}
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
        <img class="logo" src="{% static "images/project-partner-logo-2.png" %}" alt="Project Partner Logo">
            {% comment %} <h3 class="navList__route">Project Partner</h3> {% endcomment %}
            <li class="navList__route"><a class="text-decoration: none" href="{% url 'projectpartnerapp:home' %}">Home</a></li>
            <li class="navList__route"><a href="{% url 'projectpartnerapp:projects' %}">Projects</a></li>
            <li class="navList__route"><a href="{% url 'projectpartnerapp:tools' %}">Tools</a></li>
            <li class="navList__route"><a href="{% url 'projectpartnerapp:materials' %}?next={{ request.path|urlencode }}">Materials</a></li>
        {% if request.user.is_authenticated %}
            <li class="navList__route"><a href="{% url 'projectpartnerapp:logout' %}">Logout</a></li>
        {% else %}
            <li class="navList__route"><a href="{% url 'projectpartnerapp:login' %}">Login</a></li>
            <li class="navList__route"><a href="{% url 'projectpartnerapp:register' %}">Register</a></li>
        {% endif %}
        </ol>
    </nav>

    <img class="background" src="{% static "images/home-photo-collage.jpg" %}" alt="Home Project Photos">
    <main class="main-content">

        {% block content %}
        {% endblock %}
    </main>


</body>

</html>

projectpartnerproject/projectpartnerapp/templates/tools/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Project Partner</title>
  </head>
  <body>
    {% block content %}

    <h1>Tools in Inventory</h1>

    <ul style="list-style-type:none">
    {% for tool in all_tools %}

            <li>tool Name: {{ tool.name }}</li>
            <li>Description: {{tool.manufacturer}}</li>
            <li>Description: {{tool.description}}</li>
            <li>Cost: {{tool.cost}}</li>
            <li>Quantity: {{tool.own}}</li>
            <li>Project: {{tool.owner_id}}</li>
            <br></br>
    {% endfor %}
    </ul>
    <form action="{% url 'projectpartnerapp:tool' tool.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="actual_method" value="DELETE">
    <button>Delete</button>
    </form>

    <form action="{% url 'projectpartnerapp:tool_edit_form' tool.tool_id %}" method="GET">
            {% csrf_token %}
            <button>Edit tool</button>
    </form>




    {% endblock %}

  </body>
</html>

projectpartnerproject/projectpartnerapp/templates/tools/list.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Project Partner Tools</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/projects.css' %}" />
    {% endblock %}
  </head>
  <body>
  {% comment %} Displays the logged in users tool inventory. The user can delete a tool from and here and it will remove any
  instances of that tool from projects. The user can also edit any existing tools or add new tools to their inventory {% endcomment %}
    {% block content %}
    <div class="header">
    <h1>{{ user.first_name }}'s Tools</h1>
    {% comment %} <input type="hidden" name="next" value="{{ next }}"> {% endcomment %}
    <button class="btn btn-secondary"> <a href="{% url 'projectpartnerapp:new_tool_form' %}">Add New Tool </a></button>
    </div>
    <ul class="projects" style="list-style-type:none">
    {% for tool in all_tools %}
          <div class="resource">
            <li class="project__title"><strong>Tool Name:</strong> {{ tool.name }}</li>
            <li class="project__description"><strong>Manufacturer:</strong> {{ tool.manufacturer }}</li>
            <li class="project__description"><strong>Description:</strong> {{tool.description}}</li>
            <li class="project__description"><strong>Cost: $</strong>{{tool.cost}}</li>
            {% if tool.own == "off" %}
            <li class="project__description"><strong>Own this tool:</strong> No</li>
            {% elif tool.own == "on" %}
            <li class="project__description"><strong>Own this tool:</strong> Yes</li>
            {% endif %}
            <form action="{% url 'projectpartnerapp:tool' tool.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
            </form>
            <form action="{% url 'projectpartnerapp:tool_edit_form' tool.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
            </form>

           </div>
    {% endfor %}
    </ul>
    {% endblock %}
  </body>
</html>